version: '3.9'

services:
  app:
    container_name: app
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PUID=${PUID}
        - PGID=${PGID}
    restart: always
    env_file:
      - ".env"
    volumes:
      - "./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
      - ".:/var/www/html"
  db:
    container_name: db
    image: mysql:${MYSQL_VERSION}
    restart: always
    env_file:
      - ".env"
    volumes:
      - "./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf"
      - "./docker/mysql/scripts:/docker-entrypoint-initdb.d"
      - "./docker/mysql/data:/var/lib/mysql"
  web:
    container_name: web
    image: nginx:${NGINX_VERSION}
    restart: always
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/snippets/client.conf:/etc/nginx/snippets/client.conf"
      - "./docker/nginx/snippets/gzip.conf:/etc/nginx/snippets/gzip.conf"
      - "./docker/nginx/snippets/iframe.conf:/etc/nginx/snippets/iframe.conf"
      - "./docker/nginx/snippets/security.conf:/etc/nginx/snippets/security.conf"
      - ".:/var/www/html"
    depends_on:
      - app
      - db
    links:
      - db
    ports:
      - "80:80"
  admin:
    container_name: admin
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db
    links:
      - db
    ports:
      - "81:80"
