<?php defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * File_Controller class
 *
 * Should be used as parent class for all FILE related classes.
 */
class File_Controller extends MY_Controller {

	/**
	 * Constructor
	 */
	public function __construct()
	{
		parent::__construct();
	}

	// --------------------------------------------------------------------

	/**
	 * is_allowed_file
	 *
	 * Check if user has access to the file. Access key generated by unique
	 * file identificator (md5 hash of id & download_key). If $acl_key is
	 * provided and/or authorized user open file - check access for user
	 * instead.
	 *
	 * @param  int    $id
	 * @param  string $acl_key
	 * @return bool
	 */
	protected function is_allowed_file($id, $acl_key = NULL)
	{
		// by default user has access to file if $acl_key is not set
		$is_allowed = TRUE;

		if ($this->acl->logged_in() === FALSE)
		{
			$key = md5($id . $this->config->item('download_key'));
			$key_name = $this->config->item('download_key_name');

			$is_allowed = $this->input->get($key_name) === $key;
		}
		elseif (empty($acl_key) === FALSE)
		{
			$is_allowed = $this->acl->is_allowed($acl_key);
		}

		return $is_allowed;
	}

	// --------------------------------------------------------------------

	/**
	 * output_file
	 *
	 * Output file content with relevant HTTP headers to properly display in
	 * the browser.
	 *
	 * @param  string $file
	 * @param  string $file_name
	 * @return void
	 */
	protected function output_file($file, $file_name = NULL)
	{
		if (($file_content = @file_get_contents($file)) === FALSE)
		{
			set_status_header(HTTP_NOT_FOUND);
			exit(EXIT_ERROR);
		}

		$file_type = get_mime_by_extension($file);
		$file_name OR $file_name = basename($file);

		$this->output->set_header('Cache-Control: no-cache');
		$this->output->set_header('Content-Length: '.strlen($file_content));
		$this->output->set_header('Content-Disposition: inline; filename="'.$file_name.'";');
		$this->output->set_content_type($file_type);

		$this->output->_display($file_content);
		exit;
	}

}
